/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisvelasco' at '17/01/17 8:18' with Gradle 3.0
 *
 * @author luisvelasco, @date 17/01/17 8:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
